name: Run Journey Tests on GitHub
description: Run Journey Tests on GitHub

inputs:
  formsDesignerCommitHash:
    description: 'Commit hash for forms-designer repository'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: DEFRA/forms-development-tools
        path: 'forms-development-tools'

    - name: Start environment
      shell: bash
      run: |
          cd forms-development-tools/test-harness
          # Create .env file if it doesn't exist
          if [ ! -f .env ]; then
            echo "Creating missing .env file"
            touch .env
          fi
          RUN_PARAM=""
          if [ "${{ inputs.formsDesignerCommitHash }}" != "" ]; then
            RUN_PARAM="exclude=forms-designer"
          fi
          ./run-harness.sh $RUN_PARAM

    - uses: actions/checkout@v4
      if: ${{ inputs.formsDesignerCommitHash }}
      with:
        repository: DEFRA/forms-designer
        ref: ${{ inputs.formsDesignerCommitHash }}
        fetch-depth: 0
        path: 'forms-designer'
    - name: Build and run
      if: ${{ inputs.formsDesignerCommitHash }}
      shell: bash
      run: |
        cd forms-designer
        npm i
        cp designer/.automated-tests.env designer/.env
        npm run build
        echo "forms-designer" > designer-log.txt
        echo "==============" >> designer-log.txt
        npm run dev &> designer-log.txt &

    - name: Wait for designer to start serving requests
      if: ${{ inputs.formsDesignerCommitHash }}
      shell: bash
      run : |
        until curl --output /dev/null --silent --head --fail http://localhost:3000; do
          printf '.'
          sleep 5
        done

    - uses: actions/checkout@v4
      with:
        repository: DEFRA/forms-acceptance-tests
        path: 'forms-acceptance-tests'


    - name: Setup the tests
      shell: bash
      run: |
        cd forms-acceptance-tests
        npm i
    - name: Run the tests
      shell: bash
      run: |
        cd forms-acceptance-tests
        npm run test:playwright
    - name: report
      if: always()
      shell: bash
      run: |
        cd forms-acceptance-tests
        npm run report
    - name: Create allure report directory if missing
      if: always()
      shell: bash
      run: |
        cd forms-acceptance-tests
        mkdir -p allure-report
    - name: debug
      if: always()
      run: |
        echo "Docker Image Versions" >> logs.txt
        echo "=====================" >> logs.txt
        if [ -f forms-development-tools/test-harness/image-versions.txt ]; then
          cat forms-development-tools/test-harness/image-versions.txt >> logs.txt
        else
          echo "image-versions.txt not found" >> logs.txt
        fi
        echo " " >> logs.txt
        docker ps >> logs.txt
        if [ "${{ inputs.formsDesignerCommitHash }}" != "" ]; then
          echo "==============" >> logs.txt
          echo "forms-designer" >> logs.txt
          echo "==============" >> logs.txt
          cat forms-designer/designer-log.txt >> logs.txt
        fi
        containers=`docker ps | awk '{print $1}' | grep -v "CONTAINER"`
        for container in ${containers};
        do
          echo "=====================" >> logs.txt
          echo CONTAINER ${container} >> logs.txt
          echo "=====================" >> logs.txt
          docker logs ${container} >> logs.txt
        done
      shell: bash
    - name: Upload allure report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: ./forms-acceptance-tests/allure-report
        if-no-files-found: warn
    - name: Upload docker compose logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: docker-compose-logs
        path: ./logs.txt
