name: Run Journey Tests on GitHub
description: Run Journey Tests on GitHub

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: DEFRA/forms-development-tools

    - name: Start environment
      shell: bash
      run: |
          cd test-harness
          cp example.env .env
          RUN_PARAM=""
          if [ "${{ inputs.formsDesignerCommitHash }}" != "" ]; then
            RUN_PARAM="omit-designer"
          fi
          ./run-harness.sh $RUN_PARAM

    - uses: actions/checkout@v4
      with:
        repository: DEFRA/forms-acceptance-tests

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm
    - name: Setup the tests
      run: npm i
      shell: bash
    - name: Run the tests
      shell: bash
      run: |
        npm run test:playwright
        npm run report
    - name: debug
      if: always()
      run: |
        docker ps >> logs.txt
        containers=`docker ps | awk '{print $1}' | grep -v "CONTAINER"`
        for container in ${containers};
        do
          echo "=====================" >> logs.txt
          echo CONTAINER ${container} >> logs.txt
          echo "=====================" >> logs.txt
          docker logs ${container} >> logs.txt
        done
      shell: bash
    - name: Upload allure report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: ./allure-report
    - name: Upload docker compose logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: docker-compose-logs
        path: ./logs.txt
