name: Run Journey Tests on GitHub
description: Run Journey Tests on GitHub

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: DEFRA/forms-development-tools

    - name: Start environment
      shell: bash
      run: |
          cd test-harness
          echo '# forms-designer
          AZURE_CLIENT_ID="local-test-client"
          AZURE_CLIENT_SECRET="local-mock-secret"
          OIDC_WELL_KNOWN_CONFIGURATION_URL="http://localhost:5556/.well-known/openid-configuration"
          REDIS_USERNAME=default
          REDIS_PASSWORD=my-password

          FEATURE_FLAG_USE_ENTITLEMENT_API=false


          # forms-manager
          MANAGER_OIDC_JWKS_URI="http://host.docker.internal:5556/.well-known/openid-configuration/jwks"
          MANAGER_OIDC_VERIFY_AUD="local-test-client"
          MANAGER_OIDC_VERIFY_ISS="http://oidc:80"

          # forms-runner
          RUNNER_SESSION_COOKIE_PASSWORD="53409gjhfcdiklgjidfglkgjdflkelrku634"

          # submission-api
          SUBMISSION_OIDC_JWKS_URI="http://host.docker.internal:5556/.well-known/openid-configuration/jwks"
          SUBMISSION_OIDC_VERIFY_AUD="local-test-client"
          SUBMISSION_OIDC_VERIFY_ISS="http://oidc:80"

          # entitlement-api
          ENTITLEMENT_OIDC_JWKS_URI="http://host.docker.internal:5556/.well-known/openid-configuration/jwks"
          ENTITLEMENT_OIDC_VERIFY_AUD="local-test-client"
          ENTITLEMENT_OIDC_VERIFY_ISS="http://oidc:80"
          ' > .env
          ./run-harness.sh
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm
    - name: Setup the tests
      run: npm i
      shell: bash
    - name: Run the tests
      shell: bash
      run: |
        npm run test:playwright
        npm run report
    - name: debug
      if: always()
      run: |
        docker compose logs > logs.txt
        docker ps
      shell: bash
    - name: Upload allure report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: ./allure-report
    - name: Upload docker compose logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: docker-compose-logs
        path: ./logs.txt
