name: Run Journey Tests on GitHub

permissions:
  checks: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      formsDesignerCommitHash:
        description: 'forms-designer commit hash'     
        required: false
        type: string
  workflow_call:
jobs:
  build:
    name: Run Journey Tests
    runs-on: ubuntu-latest
    steps:
      - uses: DEFRA/forms-acceptance-tests/run-journey-tests@main
